serverA: severA.cpp
	g++ -std=c++11 -o serverA severA.cpp
serverB: severB.cpp
	g++ -std=c++11 -o serverB severB.cpp
serverC: severC.cpp
	g++ -std=c++11 -o serverC severC.cpp
serverM: severM.cpp
	g++ -std=c++11 -o serverM severM.cpp

client: client.cpp
	g++ -std=c++11 -o client client.cpp
monitor: monitor.cpp
	g++ -std=c++11 -o monitor monitor.cpp

clean:
	rm serverA serverB serverC serverM monitor client